### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by michaeldeistler** [jaxleyverse/jaxley#87]
- [ ] test accuracy for different radiuses
- [ ] finish resetting of conductances
- [ ] better interface for stimuli and recordings?
- [ ] `trainable_parameters`
